version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBIT_USER: guest
      RABBIT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  fastapi:
    build: .
    environment:
      - SERVICE=fastapi
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    environment:
      - SERVICE=worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

  scheduler:
    build: .
    environment:
      - SERVICE=scheduler
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

  ngrok:
    image: ngrok/ngrok:latest
    command: http fastapi:8000 --domain=${NGROK_DOMAIN}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
